//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OrinrinEditor.rc
//
#define IDC_MYICON                      2
#define IDD_ORINRINEDITOR_DIALOG        102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDC_ICON_BOX                    106
#define IDI_ORINRINEDITOR               107
#define IDI_SMALL                       108
#define IDC_ORINRINEDITOR               109
#define IDS_PANEL                       110
#define IDC_PGLVPOPUPMENU               111
#define IDC_VIEWPOPUPMENU               112
#define IDS_ORRVWR_TITLE                113
#define IDC_ORINRINVIEWER               114
#define IDD_ORRVWR_ABOUTBOX             115
#define IDD_ORRVWR_OPTION_DLG           116
#define IDI_ORINRINCOLLECTOR            117
#define IDI_COLLECTOR_SMALL             118
#define IDC_ORINRINCOLLECTOR            119
#define IDR_MAINFRAME                   128
#define IDD_UNICODE_PALETTE_DLG         129
#define IDD_FRAME_EDIT_DLG              130
#define IDD_PAGE_NAME_DLG               131
#define IDT_BACKUP_TIMER                132
#define IDD_FIND_STRING_DLG             133
#define IDD_FIND_MAA_DLG                134
#define IDD_FRAME_EDIT_DLG_2            135
#define IDD_UNICODE_PALETTE_DLG_2       136
#define IDD_TODAY_HINT_DLG              137
#define IDC_AAVIEWER                    209
#define IDD_PATH_SET                    210
#define IDSB_STATUSBAR                  211
#define IDM_AATABS_POPUP                212
#define IDM_AALIST_POPUP                213
#define IDM_AATREE_POPUP                214
#define IDM_LAYERBOX_POPUP              215
#define IDM_MULTIFILE_POPUP             217
#define IDM_TEMPLATE_POPUP              218
#define IDM_DRAUGHT_POPUP               219
#define IDD_GENERAL_OPTION_DLG          220
#define IDD_TRACEADJUST_DLG             221
#define IDD_TRACEADJUST_DLG2            222
#define IDD_MOZI_SCRIPT_DLG             223
#define IDD_IMAGE_OPEN_DLG              224
#define IDD_PROFILE_TREESEL_DLG         225
#define IDD_MSGCHECKBOX_DLG             229
#define IDD_PAGENUMBER_DLG              230
#define IDD_MAA_IADD_DLG                231
#define IDD_CONTEXT_ITEM_DLG            232
#define IDM_AAFAVS_POPUP                233
#define IDD_COLOUR_DLG                  234
#define IDD_ACCEL_KEY_DLG               235
#define IDS_MAA_TXTFIND_FIND            241
#define IDE_MAA_TXTFIND_TEXT            242
#define IDB_MAA_TXTFIND_TOP_GO          243
#define IDB_MAA_TXTFIND_NOW_GO          244
#define IDB_MAA_TXTFIND_NEXT            245
#define IDS_MAA_TXTFIND_MSGBOX          246
#define IDBMPQ_MAIN_TB_FIRST            301
#define IDBMP_FILE_NEW                  301
#define IDBMQ_FILE_NEW                  302
#define IDBMP_FILE_OPEN                 303
#define IDBMQ_FILE_OPEN                 304
#define IDBMP_FILE_SAVE                 305
#define IDBMQ_FILE_SAVE                 306
#define IDBMP_SETTING                   307
#define IDBMQ_SETTING                   308
#define IDBMPQ_EDIT_TB_FIRST            331
#define IDBMP_UNDO                      331
#define IDBMQ_UNDO                      332
#define IDBMP_REDO                      333
#define IDBMQ_REDO                      334
#define IDBMP_CUT                       335
#define IDBMQ_CUT                       336
#define IDBMP_COPY                      337
#define IDBMQ_COPY                      338
#define IDBMP_PASTE                     339
#define IDBMQ_PASTE                     340
#define IDBMP_DELETE                    341
#define IDBMQ_DELETE                    342
#define IDBMP_SJISCOPY                  343
#define IDBMQ_SJISCOPY                  344
#define IDBMP_PAGESJISCOPY              345
#define IDBMQ_PAGESJISCOPY              346
#define IDBMP_ALLSELECT                 347
#define IDBMQ_ALLSELECT                 348
#define IDBMP_BOXSELECT                 349
#define IDBMQ_BOXSELECT                 350
#define IDBMP_LAYERBOX                  351
#define IDBMQ_LAYERBOX                  352
#define IDBMP_PAGEDIVIDE                353
#define IDBMQ_PAGEDIVIDE                354
#define IDBMP_EXTRACT                   355
#define IDBMQ_EXTRACT                   356
#define IDBMP_UNICODE_MODE              357
#define IDBMQ_UNICODE_MODE              358
#define IDBMP_EXTRACTLAYER              359
#define IDBMQ_EXTRACTLAYER              360
#define IDBMPQ_INSERT_TB_FIRST          381
#define IDBMP_UNISPACE                  381
#define IDBMQ_UNISPACE                  382
#define IDBMP_COLOURTAG                 383
#define IDBMQ_COLOURTAG                 384
#define IDBMP_FRAME_INSERT              385
#define IDBMQ_FRAME_INSERT              386
#define IDBMP_USERDEF                   387
#define IDBMQ_USERDEF                   388
#define IDBMPQ_LAYOUT_TB_FIRST          401
#define IDBMP_RIGHTGUIDE                401
#define IDBMQ_RIGHTGUIDE                402
#define IDBMP_HEADSPACEADD              403
#define IDBMQ_HEADSPACEADD              404
#define IDBMP_HEADSPACEDEL              405
#define IDBMQ_HEADSPACEDEL              406
#define IDBMP_TAILSPACEDEL              407
#define IDBMQ_TAILSPACEDEL              408
#define IDBMP_TAILLETTERDEL             409
#define IDBMQ_TAILLETTERDEL             410
#define IDBMP_RIGHTSLIDE                411
#define IDBMQ_RIGHTSLIDE                412
#define IDBMP_INCREMENT_DOT             413
#define IDBMQ_INCREMENT_DOT             414
#define IDBMP_DECREMENT_DOT             415
#define IDBMQ_DECREMENT_DOT             416
#define IDBMP_LINESSHIFTRIGHT           417
#define IDBMQ_LINESSHIFTRIGHT           418
#define IDBMP_LINESSHIFTLEFT            419
#define IDBMQ_LINESSHIFTLEFT            420
#define IDBMP_MIRROR_INVERSE            421
#define IDBMQ_MIRROR_INVERSE            422
#define IDBMP_UPSET_INVERSE             423
#define IDBMQ_UPSET_INVERSE             424
#define IDBMPQ_VIEW_TB_FIRST            431
#define IDBMP_UNIPALETTE                431
#define IDBMQ_UNIPALETTE                432
#define IDBMP_TRACEMODE                 433
#define IDBMQ_TRACEMODE                 434
#define IDBMP_PREVIEW                   435
#define IDBMQ_PREVIEW                   436
#define IDBMP_DRAUGHTBOARD              437
#define IDBMQ_DRAUGHTBOARD              438
#define IDBMP_THUMBNAIL                 439
#define IDBMQ_THUMBNAIL                 440
#define IDBMP_SPLIT_LEFT                441
#define IDBMQ_SPLIT_LEFT                442
#define IDBMP_SPLIT_RIGHT               443
#define IDBMQ_SPLIT_RIGHT               444
#define IDBMPQ_PAGE_TB_FIRST            461
#define IDBMP_PAGECREATE                461
#define IDBMQ_PAGECREATE                462
#define IDBMP_PAGEINSERT                463
#define IDBMQ_PAGEINSERT                464
#define IDBMP_PAGEDUPLICATE             465
#define IDBMQ_PAGEDUPLICATE             466
#define IDBMP_PAGEDELETE                467
#define IDBMQ_PAGEDELETE                468
#define IDBMP_PAGECOMBINE               469
#define IDBMQ_PAGECOMBINE               470
#define IDBMP_PAGEUPPERSHIFT            471
#define IDBMQ_PAGEUPPERSHIFT            472
#define IDBMP_PAGEUNDERSHIFT            473
#define IDBMQ_PAGEUNDERSHIFT            474
#define IDBMP_PAGENAMECHANGE            475
#define IDBMQ_PAGENAMECHANGE            476
#define IDBMP_REFRESH                   477
#define IDBMQ_REFRESH                   478
#define IDBMP_LAYERINSERT               501
#define IDBMQ_LAYERINSERT               502
#define IDBMP_LAAYEROVERWRITE           503
#define IDBMQ_LAAYEROVERWRITE           504
#define IDBMP_LAYERTEXTEDIT             505
#define IDBMQ_LAYERTEXTEDIT             506
#define IDBMP_BRUSH_MODE                511
#define IDBMQ_BRUSH_MODE                512
#define IDBMP_PREVIEW_ALL               521
#define IDBMQ_PREVIEW_ALL               522
#define IDBMP_FRMINS_ALPHA              531
#define IDBMP_FRMINS_BRAVO              532
#define IDBMP_FRMINS_CHARLIE            533
#define IDBMP_FRMINS_DELTA              534
#define IDBMP_FRMINS_ECHO               535
#define IDBMP_FRMINS_FOXTROT            536
#define IDBMP_FRMINS_GOLF               537
#define IDBMP_FRMINS_HOTEL              538
#define IDBMP_FRMINS_INDIA              539
#define IDBMP_FRMINS_JULIETTE           540
#define IDBMP_FRMINS_KILO               541
#define IDBMP_FRMINS_LIMA               542
#define IDBMP_FRMINS_MIKE               543
#define IDBMP_FRMINS_NOVEMBER           544
#define IDBMP_FRMINS_OSCAR              545
#define IDBMP_FRMINS_POPPA              546
#define IDBMP_FRMINS_QUEBEC             547
#define IDBMP_FRMINS_ROMEO              548
#define IDBMP_FRMINS_SIERRA             549
#define IDBMP_FRMINS_TANGO              550
#define IDBMQ_FRMINS_SEL                561
#define IDBMP_FRMINS_INSERT             563
#define IDBMQ_FRMINS_INSERT             564
#define IDBMP_FRMINS_PADD               565
#define IDBMQ_FRMINS_PADD               566
#define IDBMP_MOZI_WRITE                581
#define IDBMP_MOZI_ADVANCE              583
#define IDBMQ_MOZI_ADVANCE              584
#define IDBMP_MOZI_SCRIPT               585
#define IDBMQ_MOZI_SCRIPT               586
#define IDBMP_VERT_LEFT                 587
#define IDBMQ_VERT_LEFT                 588
#define IDBMP_VERT_TRANS                589
#define IDBMQ_VERT_TRANS                590
#define IDI_TREE_DIR_CLOSE              600
#define IDI_TREE_DIR_OPEN               601
#define IDI_TREE_DIR_EXTRA              602
#define IDI_TREE_FILE_AST               603
#define IDI_TREE_FILE_MLT               604
#define IDI_TREE_FILE_ETC               605
#define IDM_TESTCODE                    999
#define IDSB_VIEW_STATUS_BAR            1000
#define IDLV_PAGELISTVIEW               1001
#define IDTB_MAIN_TOOLBAR               1002
#define IDTB_PAGE_TOOLBAR               1003
#define IDRB_REBAR                      1004
#define IDTB_LAYOUT_TOOLBAR             1005
#define IDTB_VIEW_TOOLBAR               1006
#define IDTB_EDIT_TOOLBAR               1007
#define IDTB_INSERT_TOOLBAR             1008
#define IDCB_UNI_GROUPSEL               1011
#define IDLV_UNI_CATALOGUE              1012
#define IDE_UNI_LETTER_NAME             1013
#define IDS_UNI_LETTER_IMG              1014
#define IDE_UNI_HEX_CODE                1015
#define IDE_UNI_DEC_CODE                1016
#define IDB_UNI_DECIDE                  1017
#define IDB_UNI_COPY_CLIP               1018
#define IDS_UA_ALPHA                    1019
#define IDS_UA_BRAVO                    1020
#define IDS_UA_CHARLIE                  1021
#define IDS_UA_DELTA                    1022
#define IDS_UA_ECHO                     1023
#define IDS_UA_FOXTROT                  1024
#define IDS_UA_GOLF                     1025
#define IDS_UA_HOTEL                    1026
#define IDW_LYB_TOOL_BAR                1027
#define IDE_LYB_TEXTEDIT                1028
#define IDB_OK                          1029
#define IDB_CANCEL                      1030
#define IDB_APPLY                       1031
#define IDCB_BOX_NAME_SEL               1032
#define IDE_BOXP_MORNING                1033
#define IDE_BOXP_NOON                   1034
#define IDE_BOXP_AFTERNOON              1035
#define IDE_BOXP_DAYBREAK               1036
#define IDE_BOXP_NIGHTFALL              1037
#define IDE_BOXP_TWILIGHT               1038
#define IDE_BOXP_MIDNIGHT               1039
#define IDE_BOXP_DAWN                   1040
#define IDE_LEFT_OFFSET                 1041
#define IDSP_LEFT_OFFSET                1042
#define IDE_RIGHT_OFFSET                1043
#define IDSP_RIGHT_OFFSET               1044
#define IDS_FRAME_IMAGE                 1045
#define IDE_BOXP_NAME_EDIT              1046
#define IDB_BOXP_NAME_APPLY             1047
#define IDCB_LAYER_QUICKCLOSE           1048
#define IDE_AUTO_BU_INTVL               1049
#define IDCB_AUTOBU_MSG_ON              1050
#define IDCB_LT_CATEGORY                1051
#define IDLV_LT_ITEMVIEW                1052
#define IDCB_COPY_STYLE_SWAP            1053
#define IDCB_DOCKING_STYLE              1054
#define IDTB_BT_TOOL_BAR                1055
#define IDCB_BT_CATEGORY                1056
#define IDLV_BT_ITEMVIEW                1057
#define IDW_BRUSH_TOOL_BAR              1058
#define IDTB_FRMINSBOX_TOOLBAR          1059
#define IDE_PAGENAME                    1060
#define IDCB_LAYER_EDGE_BLANK           1061
#define IDCB_UNIRADIX_HEX               1063
#define IDE_RIGHTSLIDE_DOT              1064
#define IDCB_USE_UNISPACE_SET           1065
#define IDCB_GROUPUNDO_SET              1066
#define IDSL_LAYERBOX_TRANCED           1067
#define IDRB_SEL_INS_EDIT               1068
#define IDRB_SEL_INTRPT_EDIT            1069
#define IDRB_SEL_SET_LAYER              1070
#define IDRB_SEL_CLIP_UNI               1071
#define IDRB_SEL_CLIP_SJIS              1072
#define IDRB_SEL_DRAUGHT                1073
#define IDRB_POPUP_NOMAL                1074
#define IDRB_POPUP_REDUCE               1075
#define IDCB_POPUP_VISIBLE              1076
#define IDE_ABOUT_DISP                  1077
#define IDSL_TRC_HRIZ_POS               1081
#define IDE_TRC_HRIZ_VALUE              1082
#define IDSL_TRC_VART_POS               1083
#define IDE_TRC_VART_VALUE              1084
#define IDPL_TRC_MOZICOLOUR             1085
#define IDCB_TRC_IMG_UPSET              1086
#define IDCB_TRC_IMG_MIRROR             1087
#define IDSL_TRC_CONTRAST               1088
#define IDE_TRC_CONTRAST_VALUE          1089
#define IDSL_TRC_GAMMA                  1090
#define IDE_TRC_GAMMA_VALUE             1091
#define IDSL_TRC_GRAYMOPH               1092
#define IDE_TRC_GRAYMOPH_VALUE          1093
#define IDSL_TRC_ZOOM                   1094
#define IDE_TRC_ZOOM_VALUE              1095
#define IDSL_TRC_TURN                   1096
#define IDE_TRC_TURN_VALUE              1097
#define IDB_TRC_RESET                   1098
#define IDB_TRC_VIEWTOGGLE              1099
#define IDB_TRC_IMAGEOPEN               1100
#define IDB_PRTREE_LISTUP               1101
#define IDE_PRTREE_DIR                  1102
#define IDB_PRTREE_DIR_REF              1103
#define IDTV_PRTREE_DIR_TVIEW           1104
#define IDPB_PRTREE_PROGRESS            1105
#define IDRB_CRLF_STRB                  1106
#define IDRB_CRLF_2CH_YY                1107
#define IDE_RIGHT_RULER_POS             1108
#define IDE_GRID_X_POS                  1109
#define IDE_GRID_Y_POS                  1110
#define IDE_MSC_EDITBOX                 1111
#define IDB_MSC_VWINSERT                1112
#define IDB_MSC_USELAYER                1113
#define IDE_UNDER_RULER_POS             1114
#define IDE_PAGE_BYTE_MAX               1115
#define IDCB_TRC_DLG_USETHUMB           1117
#define IDS_TRC_DLG_THUMBFRAME          1118
#define IDC_STATIC_STC32                1119
#define IDW_PVW_TOOL_BAR                1121
#define IDW_PVW_VIEW_WNDW               1122
#define IDHK_THREAD_DROP                1123
#define IDTB_DOCK_TAB                   1124
#define IDTB_MZSCR_TOOLBAR              1131
#define IDE_MZSCR_TEXT                  1132
#define IDLV_MZSCR_ISOLA                1133
#define IDLV_MZSCR_SETTING              1134
#define IDS_MZSCR_INTERVAL              1135
#define IDE_MZSCR_INTERVAL              1136
#define IDUD_MZSCR_INTERVAL             1137
#define IDCB_MZSCR_TRANSPARENT          1138
#define IDCB_MZSCR_QUICKCLOSE           1139
#define IDRB_DRT_INS_EDIT               1141
#define IDRB_DRT_INTRPT_EDIT            1142
#define IDRB_DRT_SET_LAYER              1143
#define IDRB_DRT_CLIP_UNI               1144
#define IDRB_DRT_CLIP_SJIS              1145
#define IDSB_DRT_THUM_SCROLL            1146
#define IDTT_DRT_TOOLTIP                1147
#define IDTT_TILETAB_TIP                1148
#define IDRB_SELSUB_INS_EDIT            1151
#define IDRB_SELSUB_INTRPT_EDIT         1152
#define IDRB_SELSUB_SET_LAYER           1153
#define IDRB_SELSUB_CLIP_UNI            1154
#define IDRB_SELSUB_CLIP_SJIS           1155
#define IDRB_SELSUB_DRAUGHT             1156
#define IDRB_DRTSUB_INS_EDIT            1161
#define IDRB_DRTSUB_INTRPT_EDIT         1162
#define IDRB_DRTSUB_SET_LAYER           1163
#define IDRB_DRTSUB_CLIP_UNI            1164
#define IDRB_DRTSUB_CLIP_SJIS           1165
#define IDS_VLINE_INTERVAL              1171
#define IDE_VLINE_INTERVAL              1172
#define IDUD_VLINE_INTERVAL             1173
#define IDCB_VLINE_LEFT_GO              1174
#define IDE_VLINE_TEXT                  1175
#define IDM_VLINE_DECIDE                1176
#define IDM_VLINE_REFRESH               1177
#define IDM_VLINE_TRANSPARENT           1178
#define IDCB_VLINE_QUICKCLOSE           1179
#define IDTB_VLINE_TOOLBAR              1180
#define IDS_MC_MSG1                     1191
#define IDS_MC_MSG2                     1192
#define IDCB_MC_CHECKBOX                1193
#define IDE_PN_START                    1195
#define IDE_PN_STYLE                    1196
#define IDCB_PN_UNDER                   1197
#define IDCB_PN_OVERRIDE                1198
#define IDB_MAID_NOWPAGE                1201
#define IDB_MAID_CLIPBOARD              1202
#define IDE_MAID_ITEMNAME               1203
#define IDB_MAID_ADDGO                  1204
#define IDE_MAID_CONTENTS               1205
#define IDLV_MENU_ALLITEM               1211
#define IDLV_MENU_BUILDX                1212
#define IDB_MENUITEM_ADD                1213
#define IDB_MENUITEM_DEL                1214
#define IDB_MENUITEM_SPINUP             1215
#define IDB_MENUITEM_SPINDOWN           1216
#define IDE_FIND_TEXT                   1221
#define IDCB_FIND_TARGET                1222
#define IDCB_MOD_CRLF_YEN               1223
#define IDB_FIND_CLEAR                  1224
#define IDE_MAA_FIND_NAME               1227
#define IDLV_MAA_FINDED_FILE            1228
#define IDB_COLOUR_BASIC_PEN            1231
#define IDB_COLOUR_BASIC_BACK           1232
#define IDB_COLOUR_GRID_LINE            1233
#define IDB_COLOUR_CRLF_MARK            1234
#define IDB_COLOUR_CANT_SJIS            1235
#define IDS_COLOUR_IMAGE                1236
#define IDRB_LASTOPEN_DO                1237
#define IDRB_LASTOPEN_NON               1238
#define IDRB_LASTOPEN_ASK               1239
#define IDB_CHOOSEFONT                  1240
#define IDLV_FUNCKEY_LIST               1241
#define IDHKC_FUNCKEY_INPUT             1242
#define IDB_FUNCKEY_CLEAR               1243
#define IDB_FUNCKEY_SET                 1244
#define IDB_FUNCKEY_EDIT                1245
#define IDCB_FUNCKEY_SPACE              1246
#define IDB_FUNCKEY_FILEOUT             1247
#define IDB_FUNCKEY_INIT                1248
#define IDB_FRM_PADDING                 1249
#define IDS_UNI_USE_LOG                 1250
#define IDCB_MT_CATEGORY                1251
#define IDLV_MT_ITEMSTATIC              1252
#define IDCB_MULTIACT_ENA               1253
#define IDCB_SAVE_MSG_ON                1254
#define IDS_CHAR_IMAGE                  1255
#define IDS_HINT_VIEWER                 1256
#define IDCB_NEVER_VIEWING              1257
#define IDB_NEXT_HINT                   1258
#define IDCB_POPHINT_VIEW               1260
#define IDCB_SPMOZI_ENCODE              1261
#define IDE_EXTERNAL_M2H_PATH           1262
#define IDB_EXTERNAL_M2H_SEL            1263
#define IDTV_ITEMTREE                   2000
#define IDTB_TREESEL                    2001
#define IDSO_AAITEMS                    2002
#define IDSB_LISTSCROLL                 2003
#define IDLB_FAVLIST                    2004
#define IDTB_MULTIFILE                  2005
#define IDCB_AAITEMTITLE                2006
#define IDE_AA_DIRECTORY                2010
#define IDB_AADIR_SEARCH                2011
#define IDE_CLIPSTEAL_FILE              3000
#define IDB_CLIPSTEAL_REF               3001
#define IDB_CLIP_USE_BALLOON            3002
#define IDB_CLIP_UNIRADIX_HEX           3003
#define IDB_CLIP_SAVE_AND_EXIT          3004
#define IDB_CLIPSTEAL_FILEADD           3005
#define IDB_CLIPSTEAL_FILEDEL           3006
#define IDLV_CLIPSTEAL_FILELISTVW       3007
#define IDHK_CLIPSTEAL_FILECHANGE       3008
#define IDB_CLIP_STEAL_ACT_ON           3009
#define IDHK_CLIP_POPUP_KEYBIND         3010
#define IDM_CLIPSTEAL_OPTION            32001
#define IDM_CLIPSTEAL_TOGGLE            32002
#define IDM_OPEN_HISTORY                32680
#define IDM_OPEN_HIS_FIRST              32681
#define IDM_OPEN_HIS_RESERVE            32691
#define IDM_OPEN_HIS_LAST               32692
#define IDM_OPEN_HIS_CLEAR              32693
#define IDM_TRACE_MODE_ON               32695
#define IDM_TRC_VIEWTOGGLE              32696
#define IDM_TMPL_GRID_INCREASE          32697
#define IDM_TMPL_GRID_DECREASE          32698
#define IDM_CLIPSTEAL_SELECT            32700
#define IDM_HEADHALF_EXCHANGE           32720
#define IDM_PATH_SETTING                32721
#define IDM_TREE_RECONSTRUCT            32722
#define IDM_MAA_INSERT_EDIT             32723
#define IDM_MAA_INTERRUPT_EDIT          32724
#define IDM_MAA_SET_LAYERBOX            32725
#define IDM_MAA_CLIP_UNICODE            32726
#define IDM_MAA_CLIP_SHIFTJIS           32727
#define IDM_MAA_FAV_DELETE              32728
#define IDM_MAA_AATIP_TOGGLE            32729
#define IDM_MAA_PROFILE_MAKE            32730
#define IDM_MAA_SEP_STYLE_TOGGLE        32731
#define IDM_MAA_FAVFLDR_DELETE          32732
#define IDM_MAA_RETURN_FOCUS            32733
#define IDM_COLOUR_EDIT_OPEN            32735
#define IDM_UNICODE_TOGGLE              32739
#define IDM_DUMMY                       32768
#define IDM_NEWFILE                     32771
#define IDM_OPEN                        32772
#define IDM_OVERWRITESAVE               32773
#define IDM_RENAMESAVE                  32774
#define IDM_FILE_CLOSE                  32775
#define IDM_WINDOW_CHG_RVRS             32778
#define IDM_WINDOW_CHANGE               32779
#define IDM_GENERAL_OPTION              32780
#define IDM_CUT                         32781
#define IDM_COPY                        32782
#define IDM_SJISCOPY                    32783
#define IDM_PASTE                       32784
#define IDM_DELETE                      32785
#define IDM_SQSELECT                    32786
#define IDM_ALLSEL                      32787
#define IDM_LAYERBOX                    32788
#define IDM_SJISCOPY_ALL                32789
#define IDM_RIGHT_GUIDE_SET             32791
#define IDM_RIGHT_SLIDE                 32792
#define IDM_INS_TOPSPACE                32793
#define IDM_DEL_LASTSPACE               32794
#define IDM_DEL_TOPSPACE                32795
#define IDM_DEL_LASTLETTER              32796
#define IDM_INCREMENT_DOT               32797
#define IDM_DECREMENT_DOT               32798
#define IDM_DEL_HANSPACE                32799
#define IDM_TOPMOST_TOGGLE              32800
#define IDM_DOTDIFF_LOCK                32801
#define IDM_DOTDIFF_ADJT                32802
#define IDM_PAGE_PREV                   32803
#define IDM_PAGE_NEXT                   32804
#define IDM_UNDO                        32805
#define IDM_REDO                        32806
#define IDM_SPACE_VIEW_TOGGLE           32807
#define IDM_FILL_SPACE                  32808
#define IDM_EXTRACTION_MODE             32809
#define IDM_EXTRCT_TO_LAYER             32810
#define IDM_PVW_ALLVW                   32811
#define IDM_PVW_CLOSE                   32812
#define IDM_GRID_VIEW_TOGGLE            32813
#define IDM_RIGHT_RULER_TOGGLE          32814
#define IDM_FILE_PREV                   32815
#define IDM_FILE_NEXT                   32816
#define IDM_INCR_DOT_LINES              32817
#define IDM_DECR_DOT_LINES              32818
#define IDM_UNDER_RULER_TOGGLE          32819
#define IDM_IMAGE_SAVE                  32820
#define IDM_TMPLGROUPSTYLE_TGL          32821
#define IDM_TMPLT_GROUP_PREV            32822
#define IDM_TMPLT_GROUP_NEXT            32823
#define IDM_PAGENUM_DLG_OPEN            32824
#define IDM_MENUEDIT_DLG_OPEN           32825
#define IDM_ACCELKEY_EDIT_DLG_OPEN      32826
#define IDM_SQUARE_PASTE                32827
#define IDM_FINDMAA_DLG_OPEN            32828
#define IDM_DRAUGHT_OPEN                32831
#define IDM_DRAUGHT_CLOSE               32832
#define IDM_DRAUGHT_ADDING              32833
#define IDM_DRAUGHT_DELETE              32834
#define IDM_DRAUGHT_ALLDELETE           32835
#define IDM_DRAUGHT_EXPORT              32836
#define IDM_DRAUGHT_IMPORT              32837
#define IDM_DRAUGHT_INSERTEDIT          32838
#define IDM_DRAUGHT_INTERRUPTEDIT       32839
#define IDM_DRAUGHT_LAYERBOX            32840
#define IDM_DRAUGHT_UNICLIP             32841
#define IDM_DRAUGHT_SJISCLIP            32842
#define IDM_COPY_TO_DRAUGHT             32843
#define IDM_MAA_THUMBNAIL_OPEN          32844
#define IDM_THUMB_DRAUGHT_ADD           32845
#define IDM_TMPLT_RELOAD                32846
#define IDM_VERT_SCRIPT_OPEN            32847
#define IDM_REBER_DORESET               32851
#define IDM_FIND_DLG_OPEN               32861
#define IDM_FIND_HIGHLIGHT_OFF          32862
#define IDM_FIND_JUMP_NEXT              32863
#define IDM_FIND_JUMP_PREV              32864
#define IDM_FIND_TARGET_SET             32865
#define IDM_DOT_SPLIT_RIGHT             32871
#define IDM_DOT_SPLIT_LEFT              32872
#define IDM_POSITION_RESET              32898
#define IDM_PAGEL_RETURN_FOCUS          32899
#define IDM_PAGEL_DETAIL                32900
#define IDM_PAGEL_ADD                   32901
#define IDM_PAGEL_INSERT                32902
#define IDM_PAGEL_DELETE                32903
#define IDM_PAGEL_DIVIDE                32904
#define IDM_PAGEL_COMBINE               32905
#define IDM_PAGEL_UPFLOW                32906
#define IDM_PAGEL_DOWNSINK              32907
#define IDM_PAGEL_DUPLICATE             32908
#define IDM_PAGEL_RENAME                32909
#define IDM_PAGEL_AATIP_TOGGLE          32910
#define IDM_MN_INSFRAME_SEL             32911
#define IDM_MN_USER_REFS                32912
#define IDM_BRUSH_STYLE                 32913
#define IDM_BRUSH_ON_OFF                32914
#define IDM_BRUSH_PALETTE               32915
#define IDM_MN_UNISPACE                 32916
#define IDM_MN_COLOUR_SEL               32917
#define IDM_LINE_TEMPLATE               32918
#define IDM_UNI_PALETTE                 32919
#define IDM_IN_UNI_SPACE                32920
#define IDM_IN_01SPACE                  32921
#define IDM_IN_02SPACE                  32922
#define IDM_IN_03SPACE                  32923
#define IDM_IN_04SPACE                  32924
#define IDM_IN_05SPACE                  32925
#define IDM_IN_08SPACE                  32926
#define IDM_IN_10SPACE                  32927
#define IDM_IN_16SPACE                  32928
#define IDM_INSTAG_COLOUR               32929
#define IDM_INSTAG_WHITE                32930
#define IDM_INSTAG_BLUE                 32931
#define IDM_INSTAG_BLACK                32932
#define IDM_INSTAG_RED                  32933
#define IDM_INSTAG_GREEN                32934
#define IDM_INSTAG_RESERVE              32939
#define IDM_INSFRAME_EDIT               32940
#define IDM_INSFRAME_ALPHA              32941
#define IDM_INSFRAME_BRAVO              32942
#define IDM_INSFRAME_CHARLIE            32943
#define IDM_INSFRAME_DELTA              32944
#define IDM_INSFRAME_ECHO               32945
#define IDM_INSFRAME_FOXTROT            32946
#define IDM_INSFRAME_GOLF               32947
#define IDM_INSFRAME_HOTEL              32948
#define IDM_INSFRAME_INDIA              32949
#define IDM_INSFRAME_JULIETTE           32950
#define IDM_INSFRAME_KILO               32951
#define IDM_INSFRAME_LIMA               32952
#define IDM_INSFRAME_MIKE               32953
#define IDM_INSFRAME_NOVEMBER           32954
#define IDM_INSFRAME_OSCAR              32955
#define IDM_INSFRAME_PAPA               32956
#define IDM_INSFRAME_QUEBEC             32957
#define IDM_INSFRAME_ROMEO              32958
#define IDM_INSFRAME_SIERRA             32959
#define IDM_INSFRAME_TANGO              32960
#define IDM_PAGELIST_VIEW               32961
#define IDM_ON_PREVIEW                  32962
#define IDM_FILL_ZENSP                  32963
#define IDM_FRMINSBOX_QCLOSE            32964
#define IDM_FRAME_INS_DECIDE            32965
#define IDM_FRMINSBOX_OPEN              32966
#define IDM_LINE_BRUSH_TMPL_VIEW        32967
#define IDM_FRMINSBOX_PADDING           32968
#define IDM_USERINS_NA                  32970
#define IDM_USERINS_ITEM_FIRST          32971
#define IDM_USER_ITEM_ALPHA             32971
#define IDM_USER_ITEM_BRAVO             32972
#define IDM_USER_ITEM_CHARLIE           32973
#define IDM_USER_ITEM_DELTA             32974
#define IDM_USER_ITEM_ECHO              32975
#define IDM_USER_ITEM_FOXTROT           32976
#define IDM_USER_ITEM_GOLF              32977
#define IDM_USER_ITEM_HOTEL             32978
#define IDM_USER_ITEM_INDIA             32979
#define IDM_USER_ITEM_JULIETTE          32980
#define IDM_USER_ITEM_KILO              32981
#define IDM_USER_ITEM_LIMA              32982
#define IDM_USER_ITEM_MIKE              32983
#define IDM_USER_ITEM_NOVEMBER          32984
#define IDM_USER_ITEM_OSCAR             32985
#define IDM_USER_ITEM_PAPA              32986
#define IDM_USERINS_ITEM_LAST           32986
#define IDM_LYB_INSERT                  32991
#define IDM_LYB_OVERRIDE                32992
#define IDM_LYB_DO_EDIT                 32994
#define IDM_LYB_TRANCE_RELEASE          32995
#define IDM_LYB_TRANCE_ALL              32996
#define IDM_LYB_COPY                    32997
#define IDM_LYB_DELETE                  32998
#define IDM_MAATMPLE_VIEW               33000
#define IDM_AATREE_MAINOPEN             33001
#define IDM_AATREE_SUBADD               33002
#define IDM_AATABS_DELETE               33003
#define IDM_AATREE_GOEDIT               33004
#define IDM_NOW_PAGE_REFRESH            33005
#define IDM_MAA_IADD_OPEN               33006
#define IDM_MOZI_SCR_OPEN               33007
#define IDM_MOZI_DECIDE                 33008
#define IDM_MOZI_REFRESH                33009
#define IDM_MOZI_SETTING                33010
#define IDM_MOZI_ADVANCE                33011
#define IDM_MOZI_LISTDEL                33012
#define IDM_AATABS_ALLDELETE            33013
#define IDM_MAA_ITEM_INSERT             33014
#define IDM_MAA_ITEM_DELETE             33015
#define IDM_AATABS_RENAME               33016
#define IDM_AATABS_SINGLETAB            33017
#define IDM_MIRROR_INVERSE              33021
#define IDM_UPSET_INVERSE               33022
#define IDM_MAAITEM_BKCOLOUR            33023
#define IDM_PAGENAME_SELASSIGN          33024
#define IDM_DB_THUMB_ULTRALIGHT         33032
#define IDM_DB_THUMB_REGULAR            33034
#define IDM_DB_THUMB_DEMIBOLD           33036
#define IDM_DB_THUMB_ULTRABOLD          33038
#define IDM_HTML_EXPORTE				33039
#define IDM_PLUGIN_ITEM_BASE            34000
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        236
#define _APS_NEXT_COMMAND_VALUE         33040
#define _APS_NEXT_CONTROL_VALUE         1264
#define _APS_NEXT_SYMED_VALUE           120
#endif
#endif
